import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import "../globals.css";
import { Kantumruy_Pro } from 'next/font/google';
import UnderMaintenance from "@/components/scenes/UnderMaintenance";

const nunito = Kantumruy_Pro({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-nunito',
})

const nunito_sans = Kantumruy_Pro({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-nunito-sans',
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// RootLayout now accepts 'children' and 'params'
export default async function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    // Ensure that the incoming `locale` is valid
    const { locale } = await params;
    // Setting the locale for Next-Intl
    setRequestLocale(locale);
    const siteState = process.env.SITE_STATE
    return (
        <html lang={locale}>
            <body
                className={cn(nunito.variable, nunito_sans.variable, "m-0 p-0 box-border")}
                suppressContentEditableWarning suppressHydrationWarning
            >
                <NextIntlClientProvider>
                    {
                        siteState === "maintenance" ?
                            <UnderMaintenance />
                            :
                            <>
                                {children}
                            </>
                    }
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
